include platform.conf

adjust_line_height 200%

cursor_shape block
shell_integration no-cursor
cursor_blink_interval 0

enable_audio_bell 0
window_padding_width 5
clipboard_control write-clipboard write-primary read-clipboard read-primary


# BEGIN_KITTY_THEME
# Catppuccin-Macchiato
include current-theme.conf
# END_KITTY_THEME
