font_family JetBrainsMono NF Light
italic_font JetBrainsMono NF Italic
bold_font JetBrainsMono NF Medium
bold_italic_font JetBrainsMono NF Medium Italic
font_size 13
linux_display_server wayland
hide_window_decorations yes
start_as fullscreen
