font_family JetBrainsMono Nerd Font Mono Light
italic_font JetBrainsMono Nerd Font Mono Light Italic
bold_font JetBrainsMono Nerd Font Mono Regular
bold_italic_font JetBrainsMono Nerd Font Mono Italic
font_size 16
